name: .NET Core CI

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Specify your version of .NET Core

    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages  # Path to NuGet cache
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}  # Key based on OS and .csproj hash
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # Run tests (optional)
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
