name: Deploy Project
on:
    schedule:
      - cron: '45 11 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Restore dependencies
          run: dotnet restore
  
        - name: Build the project
          run: dotnet build --configuration Release --no-restore
    
        - name: Run tests
          run: dotnet test --no-restore --verbosity normal
